name: Update GitLab Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate simple SVG
        run: |
          echo '<svg xmlns="http://www.w3.org/2000/svg" width="400" height="50">
          <rect width="400" height="50" fill="black"/>
          <text x="10" y="30" font-size="20" fill="white">GitLab Contributions (Placeholder)</text>
          </svg>' > gitlab-contributions.svg

      - name: Verify file exists
        run: ls -l gitlab-contributions.svg

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add gitlab-contributions.svg
          git commit -m "Update GitLab stats" || echo "No changes"
          git push
