name: Update GitLab Stats

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # jalan tiap jam 00:00 UTC

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          npm install axios chartjs-node-canvas

      - name: Fetch GitLab activity
        run: node ./scripts/fetch-gitlab-activity.js
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}

      - name: Generate graph
        run: node ./scripts/generate-graph.js activity.json gitlab-contributions.svg

      - name: Debug - list files
        run: ls -lah

      - name: Commit graph
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add gitlab-contributions.svg
          git commit -m "Update GitLab contributions" || echo "No changes"
          git push
