name: Update GitLab Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch GitLab Contributions
        run: |
          curl --header "PRIVATE-TOKEN: ${{ secrets.GITLAB_TOKEN }}" \
          "https://gitlab.com/api/v4/users/<USERNAME>/events" > events.json

      - name: Generate SVG
        run: |
          node <<'EOF'
          const fs = require('fs');
          const events = JSON.parse(fs.readFileSync('events.json'));
          const counts = {};
          events.forEach(e => {
            const day = e.created_at.split('T')[0];
            counts[day] = (counts[day] || 0) + 1;
          });
          let svg = `<svg xmlns="http://www.w3.org/2000/svg" width="600" height="100">`;
          let x = 10;
          for (const [day, count] of Object.entries(counts)) {
            const color = count > 5 ? "green" : count > 2 ? "lightgreen" : "gray";
            svg += `<rect x="${x}" y="10" width="10" height="10" fill="${color}">
              <title>${day}: ${count} contributions</title>
            </rect>`;
            x += 12;
          }
          svg += `</svg>`;
          fs.writeFileSync('gitlab-contributions.svg', svg);
          EOF

      - name: Verify file exists
        run: ls -l gitlab-contributions.svg

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add gitlab-contributions.svg
          git commit -m "Update GitLab stats" || echo "No changes"
          git push
