name: Update GitLab Stats

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate GitLab statistics
        uses: mona-actions/gh-gitlab-stats@main
        with:
          gitlabToken: ${{ secrets.GITLAB_TOKEN }}
          gitlabUrl: "https://dev.hummatech.com"
          gitlabUser: "Dithoss"

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update GitLab stats" || echo "No changes"
          git push
