name: Update GitLab Stats
on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate GitLab stats
        uses: Ileriayo/gitlab-contributions@v2
        with:
          gitlab_host: "https://dev.hummatech.com"
          gitlab_token: ${{ secrets.GITLAB_TOKEN }}
          gitlab_user: "Dithoss"

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update GitLab stats" || echo "No changes"
          git push
